[[collection]]
type = "entry"
link = "https://www.bilibili.com/video/BV1iq4y1u7vj/?spm_id_from=333.788.comment.all.click"
title = "尚硅谷 MySQL 8.0"

[[collection]]
type = "entry"
link = "https://db-engines.com/en/ranking"
title = "DB-Engines Ranking"
