[[collection]]
type = "entry"
link = "https://programmercarl.com/ke/bishi.html"
title = "代码随想录"

[[collection]]
type = "entry"
link = "https://www.bilibili.com/video/BV1fA4y1o715/?share_source=copy_web&vd_source=e448949c555f04421f47ebdf8e204919"
title = "代码随想录（视频）"
