[[collection]]
type = "entry"
link = "https://redis.io"
title = "官方文档"

[[collection]]
type = "entry"
link = "https://redis.io/docs/latest/commands/"
title = "命令查询"

[[collection]]
type = "entry"
link = "https://github.com/redis/redis"
title = "项目仓库"

[[collection]]
type = "entry"
link = "http://invece.org/"
title = "作者博客"

[[collection]]
type = "entry"
link = "https://www.bilibili.com/video/BV13R4y1v7sP/?share_source=copy_web&vd_source=e448949c555f04421f47ebdf8e204919"
title = "阳哥Redis7"
