[[collection]]
type = "entry"
title = "Java"

[[collection]]
type = "entry"
title = "Maven"

[[collection]]
type = "entry"
title = "Spring"

[[collection]]
type = "entry"
title = "Spring Boot"

[[collection]]
type = "entry"
title = "Spring Web MVC"

[[collection]]
type = "entry"
title = "Spring Security"

[[collection]]
type = "entry"
title = "MyBatis"

[[collection]]
type = "entry"
title = "MyBatis-Plus"

[[collection]]
type = "entry"
title = "Lombok"

[[collection]]
type = "entry"
title = "SLF4J (Logback)"
